-- =========================================================
-- Oracle SQL Practice
-- Setup database for EMP / DEPT / SALGRADE
-- =========================================================

-- 1. Tạo bảng DEPT
CREATE TABLE DEPT (
    DEPTNO NUMBER(2) CONSTRAINT PK_DEPT PRIMARY KEY,
    DNAME  VARCHAR2(14),
    LOC    VARCHAR2(13)
);

-- 2. Tạo bảng SALGRADE
CREATE TABLE SALGRADE (
    GRADE NUMBER CONSTRAINT PK_SALGRADE PRIMARY KEY,
    LOSAL NUMBER,
    HISAL NUMBER
);

-- 3. Tạo bảng EMP
CREATE TABLE EMP (
    EMPNO    NUMBER(4) CONSTRAINT PK_EMP PRIMARY KEY,
    ENAME    VARCHAR2(10),
    JOB      VARCHAR2(9),
    MGR      NUMBER(4),
    HIREDATE DATE,
    SAL      NUMBER(7,2),
    COMM     NUMBER(7,2),
    DEPTNO   NUMBER(2) CONSTRAINT NN_EMP_DEPTNO NOT NULL,

    CONSTRAINT FK_EMP_DEPT
        FOREIGN KEY (DEPTNO)
        REFERENCES DEPT(DEPTNO),

    CONSTRAINT FK_EMP_MGR
        FOREIGN KEY (MGR)
        REFERENCES EMP(EMPNO)
);

-- =========================================================
-- DATA FOR DEPT
-- =========================================================

INSERT INTO DEPT (DEPTNO, DNAME, LOC)
VALUES (10, 'ACCOUNTING', 'NEW YORK');

INSERT INTO DEPT (DEPTNO, DNAME, LOC)
VALUES (20, 'RESEARCH', 'DALLAS');

INSERT INTO DEPT (DEPTNO, DNAME, LOC)
VALUES (30, 'SALES', 'CHICAGO');

INSERT INTO DEPT (DEPTNO, DNAME, LOC)
VALUES (40, 'OPERATIONS', 'BOSTON');

-- =========================================================
-- DATA FOR SALGRADE
-- =========================================================

INSERT INTO SALGRADE (GRADE, LOSAL, HISAL)
VALUES (1, 700, 1200);

INSERT INTO SALGRADE (GRADE, LOSAL, HISAL)
VALUES (2, 1201, 1400);

INSERT INTO SALGRADE (GRADE, LOSAL, HISAL)
VALUES (3, 1401, 2000);

INSERT INTO SALGRADE (GRADE, LOSAL, HISAL)
VALUES (4, 2001, 3000);

INSERT INTO SALGRADE (GRADE, LOSAL, HISAL)
VALUES (5, 3001, 9999);

-- =========================================================
-- DATA FOR EMP
-- =========================================================

-- KING - President
INSERT INTO EMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
(7839, 'KING', 'PRESIDENT', NULL,
 TO_DATE('17-11-1981', 'DD-MM-YYYY'),
 5000, NULL, 10);

-- Managers
INSERT INTO EMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
(7698, 'BLAKE', 'MANAGER', 7839,
 TO_DATE('01-05-1981', 'DD-MM-YYYY'),
 2850, NULL, 30);

INSERT INTO EMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
(7782, 'CLARK', 'MANAGER', 7839,
 TO_DATE('09-06-1981', 'DD-MM-YYYY'),
 2450, NULL, 10);

INSERT INTO EMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
(7566, 'JONES', 'MANAGER', 7839,
 TO_DATE('02-04-1981', 'DD-MM-YYYY'),
 2975, NULL, 20);

-- Employees managed by BLAKE
INSERT INTO EMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
(7654, 'MARTIN', 'SALESMAN', 7698,
 TO_DATE('28-09-1981', 'DD-MM-YYYY'),
 1250, 1400, 30);

INSERT INTO EMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
(7499, 'ALLEN', 'SALESMAN', 7698,
 TO_DATE('20-02-1981', 'DD-MM-YYYY'),
 1600, 300, 30);

INSERT INTO EMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
(7844, 'TURNER', 'SALESMAN', 7698,
 TO_DATE('08-09-1981', 'DD-MM-YYYY'),
 1500, 0, 30);

INSERT INTO EMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
(7900, 'JAMES', 'CLERK', 7698,
 TO_DATE('03-12-1981', 'DD-MM-YYYY'),
 950, NULL, 30);

INSERT INTO EMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
(7521, 'WARD', 'SALESMAN', 7698,
 TO_DATE('22-02-1981', 'DD-MM-YYYY'),
 1250, 500, 30);

-- Employees managed by JONES
INSERT INTO EMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
(7902, 'FORD', 'ANALYST', 7566,
 TO_DATE('03-12-1981', 'DD-MM-YYYY'),
 3000, NULL, 20);

INSERT INTO EMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
(7788, 'SCOTT', 'ANALYST', 7566,
 TO_DATE('09-12-1982', 'DD-MM-YYYY'),
 3000, NULL, 20);

-- Employee managed by FORD
INSERT INTO EMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
(7369, 'SMITH', 'CLERK', 7902,
 TO_DATE('17-12-1980', 'DD-MM-YYYY'),
 800, NULL, 20);

-- Employee managed by SCOTT
INSERT INTO EMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
(7876, 'ADAMS', 'CLERK', 7788,
 TO_DATE('12-01-1983', 'DD-MM-YYYY'),
 1100, NULL, 20);

-- Employee managed by CLARK
INSERT INTO EMP
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
(7934, 'MILLER', 'CLERK', 7782,
 TO_DATE('23-01-1982', 'DD-MM-YYYY'),
 1300, NULL, 10);

COMMIT;

SELECT COUNT(*) FROM EMP;

SELECT * FROM DEPT;

SELECT * FROM SALGRADE;
