-- Oracle SQL Practice
-- Chapter 5: Join, Set Operators and Subquery

-- 1. Kết nối EMP với DEPT bằng điều kiện DEPTNO
SELECT E.ENAME,
       D.DEPTNO,
       D.DNAME
FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO;

-- 2. Kết nối bằng JOIN ... ON
SELECT E.ENAME,
       D.DNAME
FROM EMP E
JOIN DEPT D
  ON E.DEPTNO = D.DEPTNO;

-- 3. Kết nối bằng USING
SELECT E.ENAME,
       D.DNAME
FROM EMP E
JOIN DEPT D
USING (DEPTNO);

-- 4. LEFT OUTER JOIN
SELECT E.ENAME,
       D.DNAME
FROM EMP E
LEFT OUTER JOIN DEPT D
  ON E.DEPTNO = D.DEPTNO;

-- 5. RIGHT OUTER JOIN
SELECT E.ENAME,
       D.DNAME
FROM EMP E
RIGHT OUTER JOIN DEPT D
  ON E.DEPTNO = D.DEPTNO;

-- 6. FULL OUTER JOIN
SELECT E.ENAME,
       D.DNAME
FROM EMP E
FULL OUTER JOIN DEPT D
  ON E.DEPTNO = D.DEPTNO;

-- 7. SELF JOIN: nhân viên và người quản lý
SELECT E.ENAME AS EMP_NAME,
       E.SAL AS EMP_SAL,
       M.ENAME AS MGR_NAME,
       M.SAL AS MGR_SAL
FROM EMP E, EMP M
WHERE E.MGR = M.EMPNO
  AND E.SAL < M.SAL;

-- 8. CROSS JOIN
SELECT E.ENAME,
       D.DNAME
FROM EMP E
CROSS JOIN DEPT D;

-- 9. NATURAL JOIN
SELECT E.ENAME,
       D.DNAME
FROM EMP E
NATURAL JOIN DEPT D;

-- 10. UNION
SELECT JOB
FROM EMP
WHERE DEPTNO = 10
UNION
SELECT JOB
FROM EMP
WHERE DEPTNO = 30;

-- 11. UNION ALL
SELECT JOB
FROM EMP
WHERE DEPTNO = 10
UNION ALL
SELECT JOB
FROM EMP
WHERE DEPTNO = 30;

-- 12. MINUS
SELECT JOB
FROM EMP
WHERE DEPTNO = 10
MINUS
SELECT JOB
FROM EMP
WHERE DEPTNO = 30;

-- 13. INTERSECT
SELECT JOB
FROM EMP
WHERE DEPTNO = 10
INTERSECT
SELECT JOB
FROM EMP
WHERE DEPTNO = 30;

-- 14. Subquery: nhân viên có lương lớn hơn lương trung bình
SELECT ENAME,
       SAL
FROM EMP
WHERE SAL > (
    SELECT AVG(SAL)
    FROM EMP
);

-- 15. Subquery: nhân viên có lương cao nhất
SELECT ENAME,
       SAL
FROM EMP
WHERE SAL = (
    SELECT MAX(SAL)
    FROM EMP
);