-- Oracle SQL Practice
-- Chapter 8: DML and Transaction

-- Tạo bảng test để thực hành, không ảnh hưởng EMP gốc
CREATE TABLE EMP_TEST AS
SELECT *
FROM EMP
WHERE 1 = 0;

-- 1. INSERT
INSERT INTO EMP_TEST
(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO)
VALUES
(8000, 'MIKE', 'CLERK', NULL, SYSDATE, 1200, NULL, 10);

SELECT *
FROM EMP_TEST;

-- 2. UPDATE
UPDATE EMP_TEST
SET SAL = 1500
WHERE EMPNO = 8000;

SELECT EMPNO, ENAME, SAL
FROM EMP_TEST;

-- 3. SAVEPOINT
SAVEPOINT AFTER_UPDATE;

-- 4. DELETE
DELETE FROM EMP_TEST
WHERE EMPNO = 8000;

SELECT *
FROM EMP_TEST;

-- 5. ROLLBACK về SAVEPOINT
ROLLBACK TO AFTER_UPDATE;

SELECT *
FROM EMP_TEST;

-- 6. ROLLBACK toàn bộ thay đổi sau lần COMMIT trước
ROLLBACK;

-- 7. Xoá bảng test sau khi học xong
DROP TABLE EMP_TEST;
